### ISSUE TITLE
Use Service Registry Terms and Conditions check instead of Kafka

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#1086]
### Feature or problem description

Use Service Registry Terms and Conditions check instead of Kafka - when creating Registry instance

**Comment by paoloantinori** [comment]
on the UI side this is the tracker: https://issues.redhat.com/browse/MGDSTRM-5165

**Comment by wtrocki** [comment]
@paoloantinori This seems like it is resolved but we are missing technical details needed to implement it.
Is my understanding right?

**Comment by paoloantinori** [comment]
this is actually outdated, since it's been fixed directly on the RHOSR UI:
a new user that tries to use the service, is going to be redirected to the correct SR terms and condition page.

But I know how to express this problem only in terms of the UI, I don't know what impacts it could have to the CLI and if it applies at all or not

**Comment by wtrocki** [comment]
Is terms event code the same: `onlineService` ?

https://github.com/redhat-developer/app-services-cli/blob/main/internal/build/build.go#L29-L32

**Comment by wtrocki** [comment]
Done
