### ISSUE TITLE
Add abstraction of download source

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#1290]
## The problem

Currently, the CLI assumes the download source to be from upstream (GitHub release).

We now have two possible download sources: GitHub and a productised version which will be downloadable from developers.redhat.com. In the future there could be others such as DNF repositories or Brew.

There is a version checking system in place which checks only GitHub for a new version. This will produce invalid info if the user has downloaded the CLI from a different source.

## The solution

First, we need to add a build variable to indicate the build/download source. Values can be `github`, `redhat` etc.

Then, we should have an interface defining some common methods: `CheckForUpdate` initially to replicate what we have at present. There would need to be an implementation for every download source.
It could be expanded in the future to fully automate version updates from within the CLI.

**Comment by wtrocki** [comment]
My preference would be to not mix upstream releases with product. Product team should have their own answers to brew, dnf etc. We should not do it on our own and follow what other CLI from product use.

Personal opinion
 Install script is better remain github/upstream especially since we are still not 1.0 and we require people to update very often from github. Doing so many downstream releases will be unpractical and cumbersome

**Comment by wtrocki** [comment]
I do not like product leaking to upstream and also want to push to get value of productization process. Setting up call to discuss how others planning to do it as I'm aware there are discussions about generic cli publishing space thru product

**Comment by craicoverflow** [comment]
I think you are missing the point of this. This is nothing to do with dnf or yum. We have an upstream and product release, but the CLI is internally checking for new versions against upstream..t hat check should be different for the productised CLI.
