### ISSUE TITLE
Question about permissions

### ISSUE THREAD

**Issue by helio-frota** [redhat-developer/app-services-cli#1358]
hi I found this `rhoas kafka acl create --all-accounts --permission allow --operation all --topic all -y`
https://github.com/redhat-developer/app-services-cli/blob/main/.cases/acl-delete.md#cases

Any chance to run a command to have full everything permissions including Kafka instance permissions to create users and etc?

thanks

**Comment by helio-frota** [comment]
:thinking:  I think I found `rhoas kafka acl grant-admin --all-accounts --instance-id c5hv7iru4an1g84pogp0` but I'm not sure
https://github.com/redhat-developer/app-services-cli/blob/main/docs/commands/rhoas_kafka_acl_grant-admin.adoc#examples

TBH I'm not sure if my question makes sense. For example, I'm looking for a command that allows everything without worrying about consumer-group prefix or topic prefix, or user creation. 

That make sense?

**Comment by helio-frota** [comment]
Just executed the command above

```
❯ rhoas kafka acl grant-admin --all-accounts --instance-id FOO-BAR-ID-HERE
❌ Unknown flag: --instance-id. Run the command in verbose mode using the -v flag to see more information
```

**Comment by rkpattnaik780** [comment]
Hello @helio-frota !

`acl grant-admin` command gives permissions only to create acl rules to the specified user(s) or service account(s) and is not for topic/consumer-group operations. Acls need to be created separately for allowing topic and consumer-group operations.
```
rhoas kafka acl create --operation all --permission allow --group all --all-accounts
rhoas kafka acl create --operation all --permission allow --topic all --all-accounts
```
Or you can use `grant-access` command which allows producing and consuming messages
```
rhoas kafka acl grant-access --producer --consumer --all-accounts --topic all --group all
```

Hope this helps.

> ❌ Unknown flag: --instance-id

Thanks for reporting it. It will be fixed in the next release.
For now you can use `rhoas kafka use --id instance_id` before `rhoas kafka acl grant-admin` so that the command will operate on the selected Kafka instance.

**Comment by helio-frota** [comment]
@rkpattnaik780 thanks for the feedback, I'll try the commands you suggested :+1:
