### ISSUE TITLE
[Idea] turn on debug mode for all commands

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#346]
It would be quite nice to be able to persist debug mode without having to pass `--debug` all the time.

This could be in the form of a new `config` command:

```shell
$ rhoas config set debug true
Debug mode is now enabled for all commands..
```

**Comment by wtrocki** [comment]
Working on this as we agreed that we cannot release CLi with current implementation.

**Comment by wtrocki** [comment]
@craicoverflow all are `set debug true` an positional characters?

**Comment by craicoverflow** [comment]
Yes in that example, but maybe there is a better way without so many sub-commands?

```
rhoas config set-debug true
```

As an example. Not sure if this is the best way.

**Comment by wtrocki** [comment]
So I'm happy eather way. 

Do you feel that this command should enable editing any value of the config or we should support some well known use cases?

My take is that it will be easier to have multiple subcomands like set-debug etc. that handle specific cases rather than generic config writer that somewhat makes less sense as you might just open config and make edits there.

**Comment by craicoverflow** [comment]
I think we should definitely only enable specific cases and not let this give the user the ability to modify anything. Let's only enable editing the debug mode for now.
