### ISSUE TITLE
A new version of rhoas is reported when there isn't one

### ISSUE THREAD

**Issue by bibryam** [redhat-developer/app-services-cli#611]
## Description

**Version**: rhoas version 0.23.1

The CLI reports there is a new version even when you are on the latest.

### Steps to reproduce
 rhoas login 
Logging in...
Logged in successfully
Logging in to MAS-SSO...
Logged in successfully to MAS-SSO
You are now logged in as "..."
A new version of rhoas is available: 0.23.1
https://github.com/redhat-developer/app-services-cli/releases/tag/0.23.1

rhoas -v
rhoas version 0.23.1

### Expected vs actual behaviour

There should not be a message about a new version when the user is at the latest version

**Comment by craicoverflow** [comment]
Thanks for reporting this @bibryam. It hasd been fixed in https://github.com/redhat-developer/app-services-cli/pull/610, but this can't be released until we switch to production as we've already updated the default URLs to point to production, and created https://github.com/redhat-developer/app-services-cli/releases/tag/0.24.0 to get the CLI included in workshop tooling.

**Comment by craicoverflow** [comment]
Fixed now :)
