### ISSUE TITLE
Golang versions are not matching our release versions

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#633]
## Description

https://pkg.go.dev/github.com/redhat-developer/app-services-cli?tab=versions

**Comment by craicoverflow** [comment]
From [Modules Overview](https://golang.org/ref/mod#modules-overview):

> A version identifies an immutable snapshot of a module, which may be either a release or a pre-release. Each version starts with the letter v, followed by a semantic version. See Semantic Versioning 2.0.0 for details on how versions are formatted, interpreted, and compared.

> To summarize, a semantic version consists of three non-negative integers (the major, minor, and patch versions, from left to right) separated by dots. The patch version may be followed by an optional pre-release string starting with a hyphen. The pre-release string or patch version may be followed by a build metadata string starting with a plus. For example, v0.0.0, v1.12.134, v8.0.5-pre, and v2.0.9+meta are valid versions.

From this, I think the reason this is happening is because the versions have not been prefixed with "v".

We should really start prefixing the release tags with "v" going forward. This will keep the project consistent with other tools like [Odo](https://pkg.go.dev/github.com/redhat-developer/odo?tab=versions).

**Comment by craicoverflow** [comment]
Fixed now that we have prefixed tags with "v": https://pkg.go.dev/github.com/redhat-developer/app-services-cli?tab=versions
