### ISSUE TITLE
Implement the ability to change the owner of a Kafka instance

### ISSUE THREAD

**Issue by craicoverflow** [redhat-developer/app-services-cli#844]
### Feature or problem description

An organization administrator needs to be able to change the ownership of a Kafka instance to another user within the same organization.

### Proposed solution

A new PATCH endpoint will be added to the kas-fleet-manager to allow updating of fields in the Kafka instance configuration. Once added a subcommand can be added to the `kafka` command to specify changing the owner.

Here is a minimal example of how the command could be structured:

```shell
$ rhoas kafka update --owner "roger-rabbit"
Kafka instance "roger-rabbit" has been updated.
```

**Comment by wtrocki** [comment]
Would that be also a requirement for service registry? CC @ericwittman

**Comment by EricWittmann** [comment]
Good question, @wtrocki - right now we're thinking no.

The reason is that I've implemented the registry data plane security layer such that any organization admin is automatically a data plane admin for all registry instances within their org.  This is in addition to the **owner** of the registry instance also automatically being a data plane admin for that instance.

For this reason, changing the owner of a registry instance is probably not needed.

**Comment by craicoverflow** [comment]
What if you want to make a non-organization admin user the owner of a registry?

**Comment by EricWittmann** [comment]
It's really something that is up to the BU.  Here's what doing that would mean...

The new (non-org-admin) owner of the registry can:
1. Delete the registry
2. Automatically have admin-level access to the data plane of that registry

I can't think of any other benefits.  And (2) can be accomplished by granting the non-org-admin user the 'admin' role in the registry itself.

**Comment by craicoverflow** [comment]
Initial implentation is now complete.
