### ISSUE TITLE
CLI/Tooling side validation for Avro and OpenAPI schema

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-cli#917]
### Feature or problem description

We should be able to validate schema file before sending it to server.
We should look to see if we can use the same validation as backend (for consistency)

**Comment by wtrocki** [comment]
CC @paoloantinori to add some extra requirements.

**Comment by EricWittmann** [comment]
Why would we do this?  The server can perform content validation (when enabled).

**Comment by wtrocki** [comment]
@paoloantinori mention this as something that we could do.

**Comment by paoloantinori** [comment]
This was a use case extracted by the interaction with Tim's team.

The end-to-end client-server communication was failing. 
The problem triggering the failure was a validation issue.
Validation, per se, is a problem that could be solved on the client-side.
And it would make sense in a development workflow binding these checks in a Maven or npm step.

I was suggesting duplicating the server validation logic in the CLI, to allow this.
With the additional functional requirement of guaranteeing that the same exact validation logic is run on both the CLI or on the server, and not assume that the simple adherence to a format could be enough to avoid eventual bugs caused by different implementations.

**Comment by EricWittmann** [comment]
I think perhaps the solution here is to have the CLI support our existing server-side "Test" operation.  We have a REST API operation that allows a user to test whether a new version of an artifact would pass the configured rules or not, without actually doing an update.

We could introduce an additional REST API operation that could do the same thing when **creating** an artifact (we currently only support the Test operation for **updating** an artifact with a new version).

**Comment by wtrocki** [comment]
Sounds like this could be moved to apicurio registry issues?

**Comment by paoloantinori** [comment]
I still do believe that it could be interesting to have the functionality replicated on the client side, but Eric's suggested approach seems a reasonable compromise that should be addressed on the Apicurio Issues side, but you probably want to keep a corresponding task here to consume the future functionality.

**Comment by craicoverflow** [comment]
Validating user input as early as possible is generally a good idea so that the user does not have to go through multiple steps, only to see that the input was invalid after a response from the server. So if we use this "Test" operation in the CLI it should happen early in the command steps.

> operation that allows a user to test whether a new version of an artifact would pass the configured rules or not

So this validates whether the artifact would pass the configured rules, which I think is fine to do at the point where you create/update the artifact. What I think this issue is asking for is more so a generic Avro/JSON schema validation - i.e. check if these are what they are supposed to be before sending them to the server.

Something like https://github.com/xeipuuv/gojsonschema#example just simply validates the JSON schema without needing an API call.

**Comment by EricWittmann** [comment]
I'm not against client-side validation of content, so if that's what we want to do then OK.  I guess my concern is that the validation done on the server is not static, but configurable (in minor ways now, but likely in much more advanced ways in the future).  For example right now you can disable validation entirely, and the server will allow you to upload whatever you want and call it an Avro artifact.  Or you can enable syntax-only validation, which will cause the server to ensure that the content is at least syntactically valid (e.g. the content is a JSON file).  or you can enable semantic validation, which goes further to ensure that it's not just a JSON file, but it's actually semantically valid for the type you claim it is (e.g. Avro or OpenAPI).

In the future we will likely also have customizable validation (i.e. linting) where the validation can be configured at a fine-grained level.

If the CLI just does basic syntax validation on the content (based on the artifact type indicated by the user) then that seems like a fine thing to do.  But know that the CLI could pass validation and the server could still fail.  And also the CLI could **fail** validation where the server would not have.

Also note that the CLI can only validate the content if it knows what the content actually is.  So it can probably only enable validation if the user provides the artifact type.  The server is smarter because it introspects the content if no artifactType is provided by the client.

**Comment by wtrocki** [comment]
Thank you so much for context. I think safest way would be to close this for now, but feel free to reopen in case we can add some validation checks in future

**Comment by EricWittmann** [comment]
Well, I think it's been a good discussion but I'm not sure it was finished/closed.  :)

**Comment by wtrocki** [comment]
We actually have jira requirement for that feature as part of the advanced use cases. We going to close that issue as we are moving to jira issues.
